# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Package

on:
  push:
    tags:
      - v0.*
      - v1.*
  release:
    types: [published]

jobs:
  publish-package:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
          poetry --version

      - name: Build package
        run: |
          poetry build
          ls -la dist/
          echo
          echo ${{steps.get-current-branch.outputs.branch}}

      - name: Publish packages to test.pypi.org
        if: github.event_name != 'release'
        run: echo upload to test.pypi.org
#        uses: pypa/gh-action-pypi-publish@v1.4.2
#        with:
#          repository_url: https://test.pypi.org/legacy/
#          user: __token__
#          password: ${{secrets.TEST_PYPI_API_TOKEN}}
#          packages_dir: dist/

      - name: Publish packages to pypi.org
        if: github.event_name == 'release'
        run: echo upload to pypi.org
#        uses: pypa/gh-action-pypi-publish@v1.4.2
#        with:
#          user: __token__
#          password: ${{secrets.PYPI_API_TOKEN}}
#          packages_dir: dist/
